### ISSUE TITLE
Document SMTP relay configuration

### ISSUE THREAD

**Issue by drahnr** [viridIT/vSMTP#333]
**Is your feature request related to a problem? Please describe.**
Currently in the book, the section `SMTP relay` is not populated yet, which is the feature I'd like to use :)

**Describe the solution you'd like**
Document the `SMTP relay` feature to a basic point of usage including SPF

**Describe alternatives you've considered**
Status quo and remove the title until it's fully implemented (if there is anything left?)

**Comment by ltabis** [comment]
Thanks for the issue. smtp relay & spf are coming in the next release, you will be able to use those then. Since it's going to be soon, we aren't going to remove the docs about them, but we will make sure next time not to include documentation for features that do not exist yet. Thanks !

(I will keep this open until the next release)

**Comment by ltabis** [comment]
Hey @drahnr!

vSMTP 1.1 is out ! you can check out the docs [here](https://vsmtp.rs/start/configuration/hardening.html#disabling-open-relay) to configure anti-relaying rules. You can also check out the [SPF implementation](https://vsmtp.rs/advanced/eam/spf.html#vsl-predefined-function) in vsl.

I am closing this for now, feel free to re-open it if the documentation is not clear!
